using TMPro;
using UnityEngine;

/// <summary>
/// WordleKeyboardTyper
/// Lets you type letters directly into the grid generated by WordleRowsColumnGenerator
/// without clicking into a cell first — mirrors how
/// Assets/Sub/Wordle_Imported/Scripts/Board.cs already reads keyboard input every frame
/// (rather than relying on a focused TMP_InputField). Typing is confined to one row at a
/// time: once the current row is full, further letters are ignored until Enter advances
/// to the next row (Backspace only edits within the current row). Each typed letter is
/// shown with the cell's normal TMP font/text — no sprite swapping, no ImageContainer
/// dependency. If a WordleWordVerifier is assigned, pressing Enter on a full row also
/// verifies that row against the target word (coloring each cell green/yellow/plain)
/// before advancing; once a row is an exact match, the puzzle is solved and all further
/// input is ignored. Reads generator.Cells/rows/columns, which
/// WordleRowsColumnGenerator.Generate() rebuilds each time the grid is (re)generated.
/// </summary>
public class WordleKeyboardTyper : MonoBehaviour
{
    [Tooltip("The generator whose Cells this types into.")]
    public WordleRowsColumnGenerator generator;

    [Tooltip("Optional: verifies each completed row against a target word and colors cells accordingly. Leave unassigned for free typing with no win condition.")]
    public WordleWordVerifier verifier;

    private int currentRow = 0;
    private int currentColumn = 0;
    private bool solved = false;

    /// <summary>True once a row has exactly matched the target word (read by
    /// WordleTimer to stop the countdown once the puzzle is solved).</summary>
    public bool Solved => solved;

    private void Update()
    {
        if (solved)
        {
            return;
        }

        if (generator == null || generator.Cells == null || generator.Cells.Count == 0)
        {
            return;
        }

        // Keep the cursor valid if the grid was just (re)generated with different dimensions.
        currentRow = Mathf.Clamp(currentRow, 0, Mathf.Max(0, generator.rows - 1));
        currentColumn = Mathf.Clamp(currentColumn, 0, generator.columns);

        string typed = Input.inputString;
        for (int i = 0; i < typed.Length; i++)
        {
            char c = typed[i];
            if (c == '\n' || c == '\r')
            {
                TryAdvanceRow();
            }
            else if (c == '\b')
            {
                Backspace();
            }
            else if (char.IsLetter(c))
            {
                TypeLetter(c);
            }
        }
    }

    private int IndexFor(int row, int column)
    {
        return row * generator.columns + column;
    }

    private void TypeLetter(char letter)
    {
        if (currentColumn >= generator.columns)
        {
            // This row is already full — must press Enter before typing into the next row.
            return;
        }

        int index = IndexFor(currentRow, currentColumn);
        if (index < 0 || index >= generator.Cells.Count)
        {
            return;
        }

        char upper = char.ToUpperInvariant(letter);
        TMP_Text cellText = generator.Cells[index];
        cellText.text = upper.ToString();

        currentColumn++;
    }

    private void Backspace()
    {
        if (currentColumn <= 0)
        {
            // Can't back up into the previous row — it's already locked in by Enter.
            return;
        }

        currentColumn--;
        int index = IndexFor(currentRow, currentColumn);
        if (index >= 0 && index < generator.Cells.Count)
        {
            generator.Cells[index].text = string.Empty;
        }
    }

    private void TryAdvanceRow()
    {
        if (currentColumn < generator.columns)
        {
            // Current row isn't full yet — Enter only advances once every cell in the row is filled.
            return;
        }

        if (verifier != null)
        {
            bool isCorrect = verifier.VerifyRow(currentRow);
            if (isCorrect)
            {
                // Word found — stop here, no more typing accepted.
                solved = true;
                return;
            }
        }

        if (currentRow + 1 >= generator.rows)
        {
            // Already on the last row and still not solved.
            return;
        }

        currentRow++;
        currentColumn = 0;
    }
}
